[package]
name = "process_err"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
reqwest = { version = "0.12.23", features = ["blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
