[package]
name = "concurrent_programming"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = "0.8.4"
crossbeam-channel = "0.5.15"
image = "0.25.6"
lazy_static = "1.5.0"
num = "0.4.3"
num_cpus = "1.17.0"
ring = "0.17.14"
threadpool = "1.8.1"
walkdir = "2.5.0"
